name: ci

on:
  push:
    branches: ["**"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  format:
    if: github.event.repository.private
    uses: c4patino/actions/.github/workflows/format.yml@main
    with:
      language: python
  test:
    uses: oasys-mas/free-range-zoo/.github/workflows/test.yml@main
    secrets: inherit
  test-docs:
    uses: oasys-mas/free-range-zoo/.github/workflows/test-docs.yml@main
    secrets: inherit
  increment:
    needs: [format, test]
    if: >
      (github.event.repository.private) &&
      ((github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'))
    uses: c4patino/actions/.github/workflows/increment.yml@main
    with:
      language: python
  docs:
    needs: [test, test-docs]
    if: >
      (!github.event.repository.private) &&
      ((github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.ref == 'refs/heads/main'))
    uses: ./.github/workflows/docs.yml
    secrets: inherit
